services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "7001:7001"
    networks:
      - my-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "7051:7051"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

